server:
  port: 88

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu
        - id: qq_route
          uri: https://www.qq.com/
          predicates:
            - Query=url, qq
        - id: auth_route
          uri: lb://auth
          predicates:
            - Host=auth.iosoftmall.com
        - id: product_route
          uri: lb://product
          predicates:
            - Host=**.iosoftmall.com,*.iosoftmall.com 