server:
  port: 12000
  servlet:    session:      timeout: 30m

spring:
  application:
    name: auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.66
    port: 6379
  session:
    store-type: redis